### ISSUE TITLE
[streaming] net.snowflake.ingest.utils.SFException when adding a column on a destination table

### ISSUE THREAD

**Issue by BDeus** [snowflakedb/snowflake-ingest-java#511]
Hi,
Can `snowflake-ingest-sdk` be able to handle column addition on the destination table when running a java program that use the streaming ingestion ?
When i try to add a column (nullable) on the table, the channel failed and i have to handle the error and open a new one (previous channel is uncloseable since the channel not valid anymore).

Exception catch:
```
net.snowflake.ingest.utils.SFException: Channel #CHANNELNAME# is invalid and might contain uncommitted rows, please consider reopening the channel to restart.
```
_Not sure what is reopening channel, i have create a new one without closing the old one (failed if i try)._

---
I'm concern about having and option to automatically recreate a channel, because i have the same issue with `snowflake-kafka-connector` (with parameters `"snowflake.enable.schematization": "TRUE", "snowflake.ingestion.method": "SNOWPIPE_STREAMING"`).

Handling the column addition is difficult since the error is an unrecoverable one on kafka-connect.

What is the recommendation for this usecase ?

Thanks,

**Comment by sfc-gh-tzhang** [comment]
@BDeus hi, I guess there're two cases here
- If the input row has an extra column compared with the table, we don't support schema evolution currently, but will in the future, basically the extra column will be added to the table as part of the insert in the future
- If you manually add a column in the table, then it's expected that you need to reopen the channel, because the SDK doesn't know that the table schema has changed. In fact, there're many reasons a channel could become invalid (both transient and non-transient), so you should build a general logic to reopen the channel (using the same open API) and restart from the latest committed offset token for all failures.

**Comment by sfc-gh-tzhang** [comment]
@BDeus Ah, if you're talking about schema evolution in Kafka Connector, then yes, that's already supported. But my reply above is for this SDK only and we don't support schema evolution if you're using the SDK directly. 

In Kafka Connector, we based on the data type in the schema registry for evolution, what's do you have in the schema registry?

**Comment by BDeus** [comment]
Yes, i was trying both.
For me the data type "timestamp" is missing on the table schema evolution and is create as a NUMBER.
In avro schema timestamp is not a real type is just a logical type over a long.
```
{ "name": "timestamp_field", "type": { "type": "long", "logicalType": "timestamp-millis" } }
```

**Comment by sfc-gh-tzhang** [comment]
I see, I think we only have access to the type that is stored in the record schema field and that's why we create the column as NUMBER. In the future, we may be able to support a hint feature that allows customer to provide a hint on which data type we should use.

**Comment by BDeus** [comment]
Ok. I close this issue since the `SFException` is expected when the table column changed
