### ISSUE TITLE
Suppress logs from Hadoop

### ISSUE THREAD

**Issue by jdcaperon** [snowflakedb/snowflake-ingest-java#568]
Hadoop loves to log `Got brand-new compressor [.gz]`, is this something we can suppress or move to a debug/trace log level?

**Comment by sfc-gh-azagrebin** [comment]
True, I also noticed it.
The log comes from Hadoop dependency as you noticed, not in Snowpipe Streaming client SDK.
From what I see, we do not have any default log settings in the client jar.
We recommend customers to configure the logging provider that is preferred
because we use just slf4j logging API that is not an actual logging framework.

For example if you use slf4j-simple, you can set a system properties or have a settings properties file on your class path:
https://www.slf4j.org/api/org/slf4j/simple/SimpleLogger.html

**Comment by jdcaperon** [comment]
Cheers, will do :)
