### ISSUE TITLE
net.snowflake.ingest.streaming.SnowflakeStreamingIngestChannel#insertRow with the same offsetToken in the same channel produces duplicated row

### ISSUE THREAD

**Issue by xmao-zuora** [snowflakedb/snowflake-ingest-java#644]
Hi, I'm testing `net.snowflake.ingest.streaming.SnowflakeStreamingIngestChannel#insertRow` to insert row with the same `offsetToken` in the same channel, but it produced duplicated rows in table.

The doc says:
> offsetToken offset of given row, used for replay in case of failures.

So what I expect is no duplicated rows in table if calling insertRow with the same offsetToken multiple times in a same channel. Am I understanding incorrectly?

**Comment by sfc-gh-azagrebin** [comment]
Hi Daniel,

> what I expect is no duplicated rows in table if calling insertRow with the same offsetToken multiple times in a same channel

This is not what the API provides. Snowflake does not do anything with the offsetToken. The offsetToken is just stored once rows in insertRow call are committed. The purpose is to send the latest committed offsetToken to the client application in case of any disruption. The client application is supposed to know based on the latest committed offsetToken what was the actual ingest progress and where to continue ingestion from after the disruption. Calling insertRow does not mean that the rows are 100% committed because there can be disruption in distributed system: client or server side.

So if you call insertRow with the same offsetToken and same rows multiple times and there is no disruption then all attempts will be generally committed to Snowflake table with the same offsetToken. Snowflake will not deduplicate the insertRow calls based on the  offsetToken.

The example of the offsetToken usage can be upstream Kafka offset.

**Comment by xmao-zuora** [comment]
Got it, thank you!
